package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/url"
	"os"
	"sort"
	"strings"
)

const summaryCommentMarker = "<!-- px1-static-review -->"

func runSummaryComment(args []string, stdout io.Writer) error {
	fs := flag.NewFlagSet("summary-comment", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	reviewFile := fs.String("review-file", "", "path to review.json (required)")
	artifactURL := fs.String("artifact-url", "", "commit-pinned report URL (required)")
	out := fs.String("out", "", "optional file to write instead of stdout")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if strings.TrimSpace(*reviewFile) == "" || strings.TrimSpace(*artifactURL) == "" {
		return errors.New("summary-comment requires --review-file and --artifact-url")
	}
	b, err := os.ReadFile(*reviewFile)
	if err != nil {
		return fmt.Errorf("read review file: %w", err)
	}
	var report staticReviewReport
	if err := json.Unmarshal(b, &report); err != nil {
		return fmt.Errorf("decode review file: %w", err)
	}
	body, err := renderSummaryComment(report, *artifactURL)
	if err != nil {
		return err
	}
	if *out == "" {
		_, err = io.WriteString(stdout, body)
		return err
	}
	if err := os.WriteFile(*out, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write summary comment: %w", err)
	}
	return nil
}

func renderSummaryComment(report staticReviewReport, artifactURL string) (string, error) {
	if !validRevision(report.Head) {
		return "", errors.New("review head must be a full commit SHA")
	}
	parsed, err := url.Parse(strings.TrimSpace(artifactURL))
	if err != nil || (parsed.Scheme != "https" && parsed.Scheme != "http") || parsed.Host == "" {
		return "", errors.New("artifact URL must be an absolute HTTP(S) URL")
	}

	type ruleSummary struct {
		ID, Title, Severity string
		Count               int
	}
	rules := map[string]*ruleSummary{}
	for _, hit := range report.RuleHits {
		entry := rules[hit.RuleID]
		if entry == nil {
			entry = &ruleSummary{ID: hit.RuleID, Title: hit.Title, Severity: hit.Severity}
			if entry.Title == "" {
				entry.Title = hit.Message
			}
			rules[hit.RuleID] = entry
		}
		entry.Count++
	}
	highlights := make([]ruleSummary, 0, len(rules))
	for _, entry := range rules {
		highlights = append(highlights, *entry)
	}
	severityRank := map[string]int{"error": 0, "warning": 1, "info": 2}
	rank := func(severity string) int {
		if value, ok := severityRank[severity]; ok {
			return value
		}
		return 3
	}
	sort.Slice(highlights, func(i, j int) bool {
		if rank(highlights[i].Severity) != rank(highlights[j].Severity) {
			return rank(highlights[i].Severity) < rank(highlights[j].Severity)
		}
		if highlights[i].Count != highlights[j].Count {
			return highlights[i].Count > highlights[j].Count
		}
		return highlights[i].ID < highlights[j].ID
	})

	verification := "not attached"
	if report.Verification.Available {
		status := map[string]int{}
		for _, check := range report.Verification.Checks {
			status[check.Status]++
		}
		parts := []string{fmt.Sprintf("%d passed", status["passed"])}
		if status["failed"] > 0 {
			parts = append(parts, fmt.Sprintf("%d failed", status["failed"]))
		}
		pending := status["running"] + status["queued"]
		if pending > 0 {
			parts = append(parts, fmt.Sprintf("%d pending", pending))
		}
		if status["cancelled"] > 0 {
			parts = append(parts, fmt.Sprintf("%d cancelled", status["cancelled"]))
		}
		verification = strings.Join(parts, ", ")
	} else if report.Verification.Error != "" {
		verification = "unavailable (invalid or stale verification data)"
	}

	var body strings.Builder
	fmt.Fprintln(&body, summaryCommentMarker)
	fmt.Fprintln(&body, "## px1 review report")
	fmt.Fprintln(&body)
	fmt.Fprintf(&body, "Static review for commit `%s`.\n\n", report.Head)
	fmt.Fprintln(&body, "| Review signal | Result |")
	fmt.Fprintln(&body, "| --- | ---: |")
	fmt.Fprintf(&body, "| Changed files | %d |\n", len(report.Files))
	fmt.Fprintf(&body, "| Rule findings | %d |\n", len(report.RuleHits))
	fmt.Fprintf(&body, "| Attention flags | %d |\n", len(report.Attention))
	fmt.Fprintf(&body, "| AI notes | %d |\n", len(report.Explanations))
	fmt.Fprintf(&body, "| Verification | %s |\n", verification)
	if len(highlights) > 0 {
		fmt.Fprintln(&body, "\n### Rule highlights")
		for i, rule := range highlights {
			if i == 5 {
				fmt.Fprintf(&body, "- %d more rule%s in the report\n", len(highlights)-i, pluralSuffix(len(highlights)-i))
				break
			}
			fmt.Fprintf(&body, "- **%s** (`%s`, %s) — %d finding%s\n", markdownInline(rule.Title), markdownInline(rule.ID), markdownInline(rule.Severity), rule.Count, pluralSuffix(rule.Count))
		}
	}
	fmt.Fprintf(&body, "\n[Open the commit-pinned report](%s)\n\n", parsed.String())
	fmt.Fprintln(&body, "_Generated by px1; this comment is replaced when the PR head changes._")
	return body.String(), nil
}

func markdownInline(value string) string {
	value = clip(strings.ReplaceAll(value, "\n", " "), 200)
	replacer := strings.NewReplacer("\\", "\\\\", "`", "'", "*", "\\*", "_", "\\_", "[", "\\[", "]", "\\]", "<", "&lt;", ">", "&gt;", "|", "\\|")
	return replacer.Replace(value)
}

func pluralSuffix(count int) string {
	if count == 1 {
		return ""
	}
	return "s"
}
